<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Seguridad\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
  </ItemGroup>
</Project>